### ISSUE TITLE
InvalidParameterType error when calling awscii apigateway --graph-types API-calls

### ISSUE THREAD

**Issue by kyhau** [mhlabs/awscii-cli#1]
```
> awscii apigateway --id xxx --stage xxx --graph-types API-calls 

API calls last 60 minutes:
node:internal/process/promises:218
          triggerUncaughtException(err, true /* fromPromise */);
          ^

InvalidParameterType: Expected params.MetricDataQueries[0].MetricStat.Metric.Dimensions[0].Value to be a string
    at ParamValidator.fail (/home/linuxbrew/.linuxbrew/lib/node_modules/@mhlabs/awscii-cli/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateType (/home/linuxbrew/.linuxbrew/lib/node_modules/@mhlabs/awscii-cli/node_modules/aws-sdk/lib/param_validator.js:232:10)      
    at ParamValidator.validateString (/home/linuxbrew/.linuxbrew/lib/node_modules/@mhlabs/awscii-cli/node_modules/aws-sdk/lib/param_validator.js:154:32)    
    at ParamValidator.validateScalar (/home/linuxbrew/.linuxbrew/lib/node_modules/@mhlabs/awscii-cli/node_modules/aws-sdk/lib/param_validator.js:130:21)    
    at ParamValidator.validateMember (/home/linuxbrew/.linuxbrew/lib/node_modules/@mhlabs/awscii-cli/node_modules/aws-sdk/lib/param_validator.js:94:21)     
    at ParamValidator.validateStructure (/home/linuxbrew/.linuxbrew/lib/node_modules/@mhlabs/awscii-cli/node_modules/aws-sdk/lib/param_validator.js:75:14)  
    at ParamValidator.validateMember (/home/linuxbrew/.linuxbrew/lib/node_modules/@mhlabs/awscii-cli/node_modules/aws-sdk/lib/param_validator.js:88:21)     
    at ParamValidator.validateList (/home/linuxbrew/.linuxbrew/lib/node_modules/@mhlabs/awscii-cli/node_modules/aws-sdk/lib/param_validator.js:103:14)      
    at ParamValidator.validateMember (/home/linuxbrew/.linuxbrew/lib/node_modules/@mhlabs/awscii-cli/node_modules/aws-sdk/lib/param_validator.js:90:21)     
    at ParamValidator.validateStructure (/home/linuxbrew/.linuxbrew/lib/node_modules/@mhlabs/awscii-cli/node_modules/aws-sdk/lib/param_validator.js:75:14) {
  code: 'InvalidParameterType',
  time: 2021-05-04T04:52:23.156Z
}
```

**Comment by ljacobsson** [comment]
Thanks for reporting!

This is fixed in v1.0.2 :+1:
